// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using VFi.Domain.PIM.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace VFi.Infra.PIM.Mappings.Configurations
{
    public partial class CategoryConfiguration : IEntityTypeConfiguration<Category>
    {
        public void Configure(EntityTypeBuilder<Category> entity)
        {
            entity.ToTable("Category", "pim");

            entity.HasIndex(e => e.GroupCategoryId, "index_Category_GroupCategory");

            entity.HasIndex(e => e.ParentCategoryId, "index_Category_ParentCategory");

            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.Property(e => e.Code).HasMaxLength(50);

            entity.Property(e => e.CreatedByName).HasMaxLength(255);

            entity.Property(e => e.CreatedDate).HasColumnType("datetime");

            entity.Property(e => e.FullName).HasMaxLength(1000);

            entity.Property(e => e.GroupCategoryCode)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.GroupCategoryName).HasMaxLength(255);

            entity.Property(e => e.IdNumber).ValueGeneratedOnAdd();

            entity.Property(e => e.Image).HasMaxLength(255);

            entity.Property(e => e.Keywords).HasMaxLength(1000);

            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(400);

            entity.Property(e => e.ParentIds)
                .HasMaxLength(500)
                .IsUnicode(false);

            entity.Property(e => e.SourceCode)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.SourceLink).HasMaxLength(255);

            entity.Property(e => e.UpdatedByName).HasMaxLength(255);

            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");

            entity.Property(e => e.Url).HasMaxLength(255);

            entity.Property(e => e.Web).HasMaxLength(255);

            entity.HasOne(d => d.GroupCategory)
                .WithMany(p => p.Category)
                .HasForeignKey(d => d.GroupCategoryId)
                .HasConstraintName("FK_Category_Group_Category");

            entity.HasOne(d => d.ParentCategory)
                .WithMany(p => p.InverseParentCategory)
                .HasForeignKey(d => d.ParentCategoryId)
                .HasConstraintName("FK_Category_Category");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Category> entity);
    }
}
