// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using VFi.Domain.PIM.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace VFi.Infra.PIM.Mappings.Configurations
{
    public partial class CategoryRootConfiguration : IEntityTypeConfiguration<CategoryRoot>
    {
        public void Configure(EntityTypeBuilder<CategoryRoot> entity)
        {
            entity.ToTable("CategoryRoot", "pim");

            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.Property(e => e.Code).HasMaxLength(50);

            entity.Property(e => e.CreatedByName).HasMaxLength(255);

            entity.Property(e => e.CreatedDate).HasColumnType("datetime");

            entity.Property(e => e.FullName).HasMaxLength(1000);

            entity.Property(e => e.Image).HasMaxLength(255);

            entity.Property(e => e.JsonData).HasColumnType("ntext");

            entity.Property(e => e.Keywords).HasMaxLength(1000);

            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(400);

            entity.Property(e => e.ParentIds)
                .HasMaxLength(500)
                .IsUnicode(false);

            entity.Property(e => e.UpdatedByName).HasMaxLength(255);

            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");

            entity.Property(e => e.Url).HasMaxLength(255);

            entity.HasOne(d => d.ParentCategory)
                .WithMany(p => p.InverseParentCategory)
                .HasForeignKey(d => d.ParentCategoryId)
                .HasConstraintName("FK_CategoryRoot_CategoryRoot");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<CategoryRoot> entity);
    }
}
