// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using VFi.Domain.PIM.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace VFi.Infra.PIM.Mappings.Configurations
{
    public partial class DbErrorsConfiguration : IEntityTypeConfiguration<DbErrors>
    {
        public void Configure(EntityTypeBuilder<DbErrors> entity)
        {
            entity.HasNoKey();

            entity.ToTable("DB_Errors", "pim");

            entity.Property(e => e.ErrorDateTime).HasColumnType("datetime");

            entity.Property(e => e.ErrorId)
                .ValueGeneratedOnAdd()
                .HasColumnName("ErrorID");

            entity.Property(e => e.ErrorMessage).IsUnicode(false);

            entity.Property(e => e.ErrorProcedure).IsUnicode(false);

            entity.Property(e => e.UserName)
                .HasMaxLength(100)
                .IsUnicode(false);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<DbErrors> entity);
    }
}
