// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using VFi.Domain.PIM.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace VFi.Infra.PIM.Mappings.Configurations
{
    public partial class GroupCategoryConfiguration : IEntityTypeConfiguration<GroupCategory>
    {
        public void Configure(EntityTypeBuilder<GroupCategory> entity)
        {
            entity.ToTable("Group_Category", "pim");

            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.Property(e => e.Address).HasMaxLength(255);

            entity.Property(e => e.Code)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.CreatedByName).HasMaxLength(255);

            entity.Property(e => e.CreatedDate).HasColumnType("datetime");

            entity.Property(e => e.Email).HasMaxLength(255);

            entity.Property(e => e.Facebook).HasMaxLength(250);

            entity.Property(e => e.Favicon).HasMaxLength(250);

            entity.Property(e => e.Image).HasMaxLength(255);

            entity.Property(e => e.Logo).HasMaxLength(250);

            entity.Property(e => e.Logo2).HasMaxLength(250);

            entity.Property(e => e.Name).HasMaxLength(255);

            entity.Property(e => e.Phone).HasMaxLength(255);

            entity.Property(e => e.Tags).HasMaxLength(500);

            entity.Property(e => e.Title).HasMaxLength(255);

            entity.Property(e => e.UpdatedByName).HasMaxLength(255);

            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");

            entity.Property(e => e.Url).HasMaxLength(255);

            entity.Property(e => e.Youtube).HasMaxLength(250);

            entity.Property(e => e.Zalo).HasMaxLength(250);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<GroupCategory> entity);
    }
}
