// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using VFi.Domain.PIM.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace VFi.Infra.PIM.Mappings.Configurations
{
    public partial class LocalizedPropertyConfiguration : IEntityTypeConfiguration<LocalizedProperty>
    {
        public void Configure(EntityTypeBuilder<LocalizedProperty> entity)
        {
            entity.ToTable("LocalizedProperty", "pim");

            entity.Property(e => e.CreatedBy).HasMaxLength(100);

            entity.Property(e => e.LocaleKey)
                .IsRequired()
                .HasMaxLength(255);

            entity.Property(e => e.LocaleKeyGroup)
                .IsRequired()
                .HasMaxLength(150);

            entity.Property(e => e.LocaleValue).IsRequired();

            entity.Property(e => e.MasterChecksum).HasMaxLength(64);

            entity.Property(e => e.UpdatedBy).HasMaxLength(100);

            entity.HasOne(d => d.Language)
                .WithMany(p => p.LocalizedProperty)
                .HasForeignKey(d => d.LanguageId);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<LocalizedProperty> entity);
    }
}
