// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using VFi.Domain.PIM.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace VFi.Infra.PIM.Mappings.Configurations
{
    public partial class LocaleStringResourceConfiguration : IEntityTypeConfiguration<LocaleStringResource>
    {
        public void Configure(EntityTypeBuilder<LocaleStringResource> entity)
        {
            entity.ToTable("LocaleStringResource", "pim");

            entity.Property(e => e.CreatedBy).HasMaxLength(100);

            entity.Property(e => e.MasterChecksum).HasMaxLength(64);

            entity.Property(e => e.ResourceName)
                .IsRequired()
                .HasMaxLength(200);

            entity.Property(e => e.ResourceValue).IsRequired();

            entity.Property(e => e.UpdatedBy).HasMaxLength(100);

            entity.HasOne(d => d.Language)
                .WithMany(p => p.LocaleStringResource)
                .HasForeignKey(d => d.LanguageId);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<LocaleStringResource> entity);
    }
}
