// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using VFi.Domain.PIM.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace VFi.Infra.PIM.Mappings.Configurations
{
    public partial class ProductTopicPageMapConfiguration : IEntityTypeConfiguration<ProductTopicPageMap>
    {
        public void Configure(EntityTypeBuilder<ProductTopicPageMap> entity)
        {
            entity.ToTable("ProductTopicPageMap", "pim");

            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.Property(e => e.CreatedByName).HasMaxLength(255);

            entity.Property(e => e.CreatedDate).HasColumnType("datetime");

            entity.Property(e => e.ProductTopic).HasMaxLength(50);

            entity.Property(e => e.ProductTopicPage).HasMaxLength(50);

            entity.Property(e => e.UpdatedByName).HasMaxLength(255);

            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");

            entity.HasOne(d => d.ProductTopicNavigation)
                .WithMany(p => p.ProductTopicPageMap)
                .HasForeignKey(d => d.ProductTopicId)
                .HasConstraintName("FK_ProductTopicPageMap_ProductTopic");

            entity.HasOne(d => d.ProductTopicPageNavigation)
                .WithMany(p => p.ProductTopicPageMap)
                .HasForeignKey(d => d.ProductTopicPageId)
                .HasConstraintName("FK_ProductTopicPageMap_ProductTopicPage");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ProductTopicPageMap> entity);
    }
}
