// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using VFi.Domain.PIM.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace VFi.Infra.PIM.Mappings.Configurations
{
    public partial class ProductSpecificationAttributeMappingConfiguration : IEntityTypeConfiguration<ProductSpecificationAttributeMapping>
    {
        public void Configure(EntityTypeBuilder<ProductSpecificationAttributeMapping> entity)
        {
            entity.ToTable("Product_SpecificationAttribute_Mapping", "pim");

            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.HasOne(d => d.Product)
                .WithMany(p => p.ProductSpecificationAttributeMapping)
                .HasForeignKey(d => d.ProductId);

            entity.HasOne(d => d.SpecificationAttributeOption)
                .WithMany(p => p.ProductSpecificationAttributeMapping)
                .HasForeignKey(d => d.SpecificationAttributeOptionId);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ProductSpecificationAttributeMapping> entity);
    }
}
