// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using VFi.Domain.PIM.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace VFi.Infra.PIM.Mappings.Configurations
{
    public partial class ProductReviewHelpfulnessConfiguration : IEntityTypeConfiguration<ProductReviewHelpfulness>
    {
        public void Configure(EntityTypeBuilder<ProductReviewHelpfulness> entity)
        {
            entity.ToTable("ProductReviewHelpfulness", "pim");

            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.HasOne(d => d.ProductReview)
                .WithMany(p => p.ProductReviewHelpfulness)
                .HasForeignKey(d => d.ProductReviewId)
                .OnDelete(DeleteBehavior.ClientSetNull);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ProductReviewHelpfulness> entity);
    }
}
