// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using VFi.Domain.PIM.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace VFi.Infra.PIM.Mappings.Configurations
{
    public partial class ProductStoreMappingConfiguration : IEntityTypeConfiguration<ProductStoreMapping>
    {
        public void Configure(EntityTypeBuilder<ProductStoreMapping> entity)
        {
            entity.ToTable("ProductStoreMapping", "pim");

            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.HasOne(d => d.Product)
                .WithMany(p => p.ProductStoreMapping)
                .HasForeignKey(d => d.ProductId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK_ProductStoreMapping_Product");

            entity.HasOne(d => d.Store)
                .WithMany(p => p.ProductStoreMapping)
                .HasForeignKey(d => d.StoreId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK_ProductStoreMapping_Store");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ProductStoreMapping> entity);
    }
}
