// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using VFi.Domain.PIM.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace VFi.Infra.PIM.Mappings.Configurations
{
    public partial class ProductTopicPageConfiguration : IEntityTypeConfiguration<ProductTopicPage>
    {
        public void Configure(EntityTypeBuilder<ProductTopicPage> entity)
        {
            entity.ToTable("ProductTopicPage", "pim");

            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.Property(e => e.Code)
                .IsRequired()
                .HasMaxLength(50);

            entity.Property(e => e.CreatedByName).HasMaxLength(255);

            entity.Property(e => e.CreatedDate).HasColumnType("datetime");

            entity.Property(e => e.Icon).HasMaxLength(250);

            entity.Property(e => e.Icon2).HasMaxLength(250);

            entity.Property(e => e.Image).HasMaxLength(255);

            entity.Property(e => e.Keywords).HasMaxLength(255);

            entity.Property(e => e.Name).HasMaxLength(255);

            entity.Property(e => e.Slug)
                .HasMaxLength(250)
                .IsUnicode(false);

            entity.Property(e => e.Tags).HasMaxLength(500);

            entity.Property(e => e.Title).HasMaxLength(255);

            entity.Property(e => e.UpdatedByName).HasMaxLength(255);

            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ProductTopicPage> entity);
    }
}
