// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using VFi.Domain.PIM.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace VFi.Infra.PIM.Mappings.Configurations
{
    public partial class ProductProductAttributeMappingConfiguration : IEntityTypeConfiguration<ProductProductAttributeMapping>
    {
        public void Configure(EntityTypeBuilder<ProductProductAttributeMapping> entity)
        {
            entity.ToTable("Product_ProductAttribute_Mapping", "pim");

            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.Property(e => e.TextPrompt).HasMaxLength(4000);

            entity.HasOne(d => d.ProductAttribute)
                .WithMany(p => p.ProductProductAttributeMapping)
                .HasForeignKey(d => d.ProductAttributeId);

            entity.HasOne(d => d.Product)
                .WithMany(p => p.ProductProductAttributeMapping)
                .HasForeignKey(d => d.ProductId);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ProductProductAttributeMapping> entity);
    }
}
