// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using VFi.Domain.PIM.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace VFi.Infra.PIM.Mappings.Configurations
{
    public partial class ProductSpecificationCodeConfiguration : IEntityTypeConfiguration<ProductSpecificationCode>
    {
        public void Configure(EntityTypeBuilder<ProductSpecificationCode> entity)
        {
            entity.ToTable("ProductSpecificationCode", "pim");

            entity.HasComment("Bảng tồn theo quy cách");

            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(255);

            entity.HasOne(d => d.Product)
                .WithMany(p => p.ProductSpecificationCode)
                .HasForeignKey(d => d.ProductId)
                .HasConstraintName("FK_ProductSpecificationCode_Product");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ProductSpecificationCode> entity);
    }
}
