// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using VFi.Domain.PIM.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace VFi.Infra.PIM.Mappings.Configurations
{
    public partial class ProductGroupCategoryMappingConfiguration : IEntityTypeConfiguration<ProductGroupCategoryMapping>
    {
        public void Configure(EntityTypeBuilder<ProductGroupCategoryMapping> entity)
        {
            entity.ToTable("Product_GroupCategory_Mapping", "pim");

            entity.HasIndex(e => e.ProductId, "index_Product_GroupCategory_Mapping_ProductId");

            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.HasOne(d => d.GroupCategory)
                .WithMany(p => p.ProductGroupCategoryMapping)
                .HasForeignKey(d => d.GroupCategoryId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK_Product_GroupCategory_Mapping_Group_Category");

            entity.HasOne(d => d.Product)
                .WithMany(p => p.ProductGroupCategoryMapping)
                .HasForeignKey(d => d.ProductId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK_Product_GroupCategory_Mapping_Product");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ProductGroupCategoryMapping> entity);
    }
}
