// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using VFi.Domain.PIM.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace VFi.Infra.PIM.Mappings.Configurations
{
    public partial class ProductInventoryDetailConfiguration : IEntityTypeConfiguration<ProductInventoryDetail>
    {
        public void Configure(EntityTypeBuilder<ProductInventoryDetail> entity)
        {
            entity.ToTable("ProductInventoryDetail", "pim");

            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.Property(e => e.CreatedByName).HasMaxLength(150);

            entity.Property(e => e.CreatedDate).HasColumnType("datetime");

            entity.Property(e => e.ExpireDate).HasColumnType("date");

            entity.Property(e => e.LotNumber).HasMaxLength(50);

            entity.Property(e => e.UnitCode)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasComment("Đơn vị tính");

            entity.Property(e => e.UnitName).HasMaxLength(50);

            entity.Property(e => e.UnitType)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.UpdatedByName).HasMaxLength(150);

            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");

            entity.HasOne(d => d.ProductInventory)
                .WithMany(p => p.ProductInventoryDetail)
                .HasForeignKey(d => d.ProductInventoryId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK_ProductInventoryDetail_ProductInventory");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ProductInventoryDetail> entity);
    }
}
