// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using VFi.Domain.PIM.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace VFi.Infra.PIM.Mappings.Configurations
{
    public partial class ProductCategoryMappingConfiguration : IEntityTypeConfiguration<ProductCategoryMapping>
    {
        public void Configure(EntityTypeBuilder<ProductCategoryMapping> entity)
        {
            entity.ToTable("Product_Category_Mapping", "pim");

            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.HasOne(d => d.Category)
                .WithMany(p => p.ProductCategoryMapping)
                .HasForeignKey(d => d.CategoryId);

            entity.HasOne(d => d.Product)
                .WithMany(p => p.ProductCategoryMapping)
                .HasForeignKey(d => d.ProductId);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ProductCategoryMapping> entity);
    }
}
