// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using VFi.Domain.PIM.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace VFi.Infra.PIM.Mappings.Configurations
{
    public partial class ProductProductTagMappingConfiguration : IEntityTypeConfiguration<ProductProductTagMapping>
    {
        public void Configure(EntityTypeBuilder<ProductProductTagMapping> entity)
        {
            entity.ToTable("Product_ProductTag_Mapping", "pim");

            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.Property(e => e.ProductId).HasColumnName("Product_Id");

            entity.Property(e => e.ProductTagId).HasColumnName("ProductTag_Id");

            entity.HasOne(d => d.Product)
                .WithMany(p => p.ProductProductTagMapping)
                .HasForeignKey(d => d.ProductId)
                .HasConstraintName("FK_dbo.Product_ProductTag_Mapping_dbo.Product_Product_Id");

            entity.HasOne(d => d.ProductTag)
                .WithMany(p => p.ProductProductTagMapping)
                .HasForeignKey(d => d.ProductTagId)
                .HasConstraintName("FK_dbo.Product_ProductTag_Mapping_dbo.ProductTag_ProductTag_Id");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ProductProductTagMapping> entity);
    }
}
