// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using VFi.Domain.PIM.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace VFi.Infra.PIM.Mappings.Configurations
{
    public partial class ProductWarehouseConfiguration : IEntityTypeConfiguration<ProductWarehouse>
    {
        public void Configure(EntityTypeBuilder<ProductWarehouse> entity)
        {
            entity.ToTable("ProductWarehouse", "pim");

            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.Property(e => e.CreatedByDate).HasColumnType("datetime");

            entity.Property(e => e.CreatedName).HasMaxLength(255);

            entity.Property(e => e.PlannedQuantity)
                .HasDefaultValueSql("((0))")
                .HasComment("Số lượng kế hoạch");

            entity.Property(e => e.UpdatedByDate).HasColumnType("datetime");

            entity.Property(e => e.UpdatedName).HasMaxLength(255);

            entity.HasOne(d => d.Product)
                .WithMany(p => p.ProductWarehouse)
                .HasForeignKey(d => d.ProductId)
                .HasConstraintName("FK_ProductWarehouse_Product");

            entity.HasOne(d => d.Warehouse)
                .WithMany(p => p.ProductWarehouse)
                .HasForeignKey(d => d.WarehouseId)
                .HasConstraintName("FK_ProductWarehouse_Warehouse");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ProductWarehouse> entity);
    }
}
