// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using VFi.Domain.PIM.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace VFi.Infra.PIM.Mappings.Configurations
{
    public partial class ProductTopicDetailConfiguration : IEntityTypeConfiguration<ProductTopicDetail>
    {
        public void Configure(EntityTypeBuilder<ProductTopicDetail> entity)
        {
            entity.ToTable("ProductTopicDetail", "pim");

            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.Property(e => e.BidPrice).HasColumnType("money");

            entity.Property(e => e.Brand).HasMaxLength(255);

            entity.Property(e => e.Channel).HasMaxLength(50);

            entity.Property(e => e.Code).HasMaxLength(50);

            entity.Property(e => e.Condition).HasComment("New = 0, Refurbished = 10, Used = 20, Damaged = 30");

            entity.Property(e => e.CreatedByName).HasMaxLength(255);

            entity.Property(e => e.CreatedDate).HasColumnType("datetime");

            entity.Property(e => e.Currency).HasMaxLength(50);

            entity.Property(e => e.Exp).HasColumnType("datetime");

            entity.Property(e => e.Image).HasMaxLength(500);

            entity.Property(e => e.Keywords).HasMaxLength(500);

            entity.Property(e => e.Manufacturer).HasMaxLength(255);

            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(400);

            entity.Property(e => e.Origin).HasMaxLength(255);

            entity.Property(e => e.Price).HasColumnType("money");

            entity.Property(e => e.ProductTopic)
                .IsRequired()
                .HasMaxLength(50);

            entity.Property(e => e.ProductType).HasMaxLength(250);

            entity.Property(e => e.PublishDate).HasColumnType("datetime");

            entity.Property(e => e.Seller).HasMaxLength(250);

            entity.Property(e => e.ShippingFee).HasColumnType("money");

            entity.Property(e => e.ShortDescription).HasMaxLength(4000);

            entity.Property(e => e.SourceCode).HasMaxLength(50);

            entity.Property(e => e.SourceLink).HasMaxLength(250);

            entity.Property(e => e.Tags).HasMaxLength(1000);

            entity.Property(e => e.TopicQuery).HasMaxLength(250);

            entity.Property(e => e.Unit).HasMaxLength(50);

            entity.Property(e => e.UpdatedByName).HasMaxLength(255);

            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");

            entity.HasOne(d => d.ProductTopicNavigation)
                .WithMany(p => p.ProductTopicDetail)
                .HasForeignKey(d => d.ProductTopicId)
                .HasConstraintName("FK_ProductTopicDetail_ProductTopic");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ProductTopicDetail> entity);
    }
}
