// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using VFi.Domain.PIM.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace VFi.Infra.PIM.Mappings.Configurations
{
    public partial class ProductInventoryConfiguration : IEntityTypeConfiguration<ProductInventory>
    {
        public void Configure(EntityTypeBuilder<ProductInventory> entity)
        {
            entity.ToTable("ProductInventory", "pim");

            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.Property(e => e.CreatedByName).HasMaxLength(255);

            entity.Property(e => e.CreatedDate).HasColumnType("datetime");

            entity.Property(e => e.SpecificationCode1)
                .HasMaxLength(250)
                .HasComment("Mã quy cách 1");

            entity.Property(e => e.SpecificationCode10).HasMaxLength(250);

            entity.Property(e => e.SpecificationCode2)
                .HasMaxLength(250)
                .HasComment("Mã quy cách 1");

            entity.Property(e => e.SpecificationCode3)
                .HasMaxLength(250)
                .HasComment("Mã quy cách 1");

            entity.Property(e => e.SpecificationCode4)
                .HasMaxLength(250)
                .HasComment("Mã quy cách 1");

            entity.Property(e => e.SpecificationCode5)
                .HasMaxLength(250)
                .HasComment("Mã quy cách 1");

            entity.Property(e => e.SpecificationCode6)
                .HasMaxLength(250)
                .HasComment("Mã quy cách 1");

            entity.Property(e => e.SpecificationCode7)
                .HasMaxLength(250)
                .HasComment("Mã quy cách 1");

            entity.Property(e => e.SpecificationCode8)
                .HasMaxLength(250)
                .HasComment("Mã quy cách 1");

            entity.Property(e => e.SpecificationCode9)
                .HasMaxLength(250)
                .HasComment("Mã quy cách 1");

            entity.Property(e => e.UpdatedByName).HasMaxLength(255);

            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");

            entity.HasOne(d => d.Product)
                .WithMany(p => p.ProductInventory)
                .HasForeignKey(d => d.ProductId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK_ProductInventory_Product");

            entity.HasOne(d => d.Warehouse)
                .WithMany(p => p.ProductInventory)
                .HasForeignKey(d => d.WarehouseId)
                .HasConstraintName("FK_ProductInventory_Warehouse");

            entity.HasOne(d => d.Unit)
              .WithMany(p => p.ProductInventory)
              .HasForeignKey(d => d.UnitId)
              .HasConstraintName("FK_ProductInventory_Unit");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ProductInventory> entity);
    }
}
