// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using VFi.Domain.PIM.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace VFi.Infra.PIM.Mappings.Configurations
{
    public partial class ServiceAddPriceSyntaxConfiguration : IEntityTypeConfiguration<ServiceAddPriceSyntax>
    {
        public void Configure(EntityTypeBuilder<ServiceAddPriceSyntax> entity)
        {
            entity.ToTable("ServiceAddPriceSyntax", "pim");

            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.Property(e => e.Code)
                .HasMaxLength(255)
                .IsUnicode(false);

            entity.Property(e => e.CreatedDate).HasColumnType("datetime");

            entity.Property(e => e.CreatedName).HasMaxLength(50);

            entity.Property(e => e.Description).HasColumnType("ntext");

            entity.Property(e => e.Formula)
                .HasColumnType("ntext")
                .HasComment("Công thức");

            entity.Property(e => e.Name).HasMaxLength(255);

            entity.Property(e => e.TypeValue).HasComment("Kiểu giá trị: 0-Số, 1-Tiền tệ, 2-Phần trăm, 3-Chữ, 4-Ngày, 5-Checkbox");

            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");

            entity.Property(e => e.UpdatedName).HasMaxLength(50);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ServiceAddPriceSyntax> entity);
    }
}
