// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using VFi.NetDevPack.Domain;
using System;
using System.Collections.Generic;

namespace VFi.Domain.PIM.Models
{
    public partial class CategoryRoot : Entity, IAggregateRoot
    {
        public CategoryRoot()
        {
            InverseParentCategory = new HashSet<CategoryRoot>();
            Product = new HashSet<Product>();
        }

        public string Code { get; set; }
        public string Name { get; set; }
        public string FullName { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }
        public string Url { get; set; }
        public Guid? ParentCategoryId { get; set; }
        public string Keywords { get; set; }
        public string JsonData { get; set; }
        public int Status { get; set; }
        public int DisplayOrder { get; set; }
        public DateTime? CreatedDate { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public Guid? CreatedBy { get; set; }
        public Guid? UpdatedBy { get; set; }
        public string CreatedByName { get; set; }
        public string UpdatedByName { get; set; }
        public int IdNumber { get; set; }
        public string ParentIds { get; set; }
        public int? Level { get; set; }

        public virtual CategoryRoot ParentCategory { get; set; }
        public virtual ICollection<CategoryRoot> InverseParentCategory { get; set; }
        public virtual ICollection<Product> Product { get; set; }
    }
}