// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using VFi.NetDevPack.Domain;
using System;
using System.Collections.Generic;

namespace VFi.Domain.PIM.Models
{
    public partial class DeliveryTime : Entity, IAggregateRoot
    {
        public DeliveryTime()
        {
            Product = new HashSet<Product>();
        }
         
        public string Name { get; set; }
        public bool? IsDefault { get; set; }
        public int? MinDays { get; set; }
        public int? MaxDays { get; set; }
        public int DisplayOrder { get; set; }
        public int? Status { get; set; }
        public DateTime CreatedDate { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public Guid? CreatedBy { get; set; }
        public Guid? UpdatedBy { get; set; }
        public string CreatedByName { get; set; }
        public string UpdatedByName { get; set; }

        public virtual ICollection<Product> Product { get; set; }
    }
}