// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using VFi.NetDevPack.Domain;
using System;
using System.Collections.Generic;

namespace VFi.Domain.PIM.Models
{
    public partial class GroupCategory : Entity, IAggregateRoot
    {
        public GroupCategory()
        {
            Category = new HashSet<Category>();
            ProductGroupCategoryMapping = new HashSet<ProductGroupCategoryMapping>();
        }
         
        public string Code { get; set; }
        public string Name { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }
        public string Logo { get; set; }
        public string Logo2 { get; set; }
        public string Favicon { get; set; }
        public string Url { get; set; }
        public string Tags { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public string Facebook { get; set; }
        public string Youtube { get; set; }
        public string Zalo { get; set; }
        public int Status { get; set; }
        public bool? IsDefault { get; set; }
        public int DisplayOrder { get; set; }
        public DateTime CreatedDate { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public Guid? CreatedBy { get; set; }
        public Guid? UpdatedBy { get; set; }
        public string CreatedByName { get; set; }
        public string UpdatedByName { get; set; }

        public virtual ICollection<Category> Category { get; set; }
        public virtual ICollection<ProductGroupCategoryMapping> ProductGroupCategoryMapping { get; set; }
    }
}