// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using VFi.NetDevPack.Domain;
using System;
using System.Collections.Generic;

namespace VFi.Domain.PIM.Models
{
    public partial class LocaleStringResource : Entity, IAggregateRoot
    {
        public int LanguageId { get; set; }
        public string ResourceName { get; set; }
        public string ResourceValue { get; set; }
        public bool? IsFromPlugin { get; set; }
        public bool? IsTouched { get; set; }
        public DateTime CreatedOnUtc { get; set; }
        public DateTime? UpdatedOnUtc { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public string MasterChecksum { get; set; }

        public virtual Language Language { get; set; }
    }
}