// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using VFi.NetDevPack.Domain;
using System;
using System.Collections.Generic;

namespace VFi.Domain.PIM.Models
{
    /// <summary>
    /// Bảng tồn theo quy cách
    /// </summary>
    public partial class ProductSpecificationCode : Entity, IAggregateRoot
    {
        public Guid ProductId { get; set; }
        public string Name { get; set; }
        public bool DuplicateAllowed { get; set; }
        public int Status { get; set; }
        public int DataTypes { get; set; }
        public int DisplayOrder { get; set; }

        public virtual Product Product { get; set; }
    }
}