// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using VFi.NetDevPack.Domain;
using System;
using System.Collections.Generic;

namespace VFi.Domain.PIM.Models
{
    public partial class ProductGroupCategoryMapping : Entity, IAggregateRoot
    {
        public Guid? ProductId { get; set; }
        public Guid? GroupCategoryId { get; set; }
        public int? DisplayOrder { get; set; }

        public virtual GroupCategory GroupCategory { get; set; }
        public virtual Product Product { get; set; }
    }
}