// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using VFi.NetDevPack.Domain;
using System;
using System.Collections.Generic;

namespace VFi.Domain.PIM.Models
{
    public partial class ProductTopicPageMap : Entity, IAggregateRoot
    {
        public Guid ProductTopicPageId { get; set; }
        public Guid ProductTopicId { get; set; }
        public string ProductTopicPage { get; set; }
        public string ProductTopic { get; set; }
        public int DisplayOrder { get; set; }
        public DateTime CreatedDate { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public Guid? CreatedBy { get; set; }
        public Guid? UpdatedBy { get; set; }
        public string CreatedByName { get; set; }
        public string UpdatedByName { get; set; }

        public virtual ProductTopic ProductTopicNavigation { get; set; }
        public virtual ProductTopicPage ProductTopicPageNavigation { get; set; }
    }
}