// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using VFi.NetDevPack.Domain;
using System;
using System.Collections.Generic;

namespace VFi.Domain.PIM.Models
{
    public partial class ProductTopic : Entity, IAggregateRoot
    {
        public ProductTopic()
        {
            ProductTopicDetail = new HashSet<ProductTopicDetail>();
            ProductTopicPageMap = new HashSet<ProductTopicPageMap>();
            ProductTopicQuery = new HashSet<ProductTopicQuery>();
        }
         
        public string Code { get; set; }
        public string? Slug { get; set; }
        public string? Name { get; set; }
        public string? Title { get; set; }
        public string? Description { get; set; }
        public string? Keywords { get; set; }
        public string? Image { get; set; }
        public string? Icon { get; set; }
        public string? Icon2 { get; set; }
        public string? Tags { get; set; }
        public int Status { get; set; }
        public int DisplayOrder { get; set; }
        public DateTime CreatedDate { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public Guid? CreatedBy { get; set; }
        public Guid? UpdatedBy { get; set; }
        public string CreatedByName { get; set; }
        public string UpdatedByName { get; set; }

        public virtual ICollection<ProductTopicDetail> ProductTopicDetail { get; set; }
        public virtual ICollection<ProductTopicPageMap> ProductTopicPageMap { get; set; }
        public virtual ICollection<ProductTopicQuery> ProductTopicQuery { get; set; }
    }
}