// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using VFi.NetDevPack.Domain;
using System;
using System.Collections.Generic;

namespace VFi.Domain.PIM.Models
{
    public partial class ProductVariantAttributeCombination : Entity, IAggregateRoot
    {
        public string? Name { get; set; }
        public Guid ProductId { get; set; }
        public string? Sku { get; set; }
        public string? Gtin { get; set; }
        public string? ManufacturerPartNumber { get; set; }
        public decimal? Price { get; set; }
        public decimal? Length { get; set; }
        public decimal? Width { get; set; }
        public decimal? Height { get; set; }
        public decimal? BasePriceAmount { get; set; }
        public int? BasePriceBaseAmount { get; set; }
        public string? AssignedMediaFileIds { get; set; }
        public bool IsActive { get; set; }
        public Guid? DeliveryTimeId { get; set; }
        public Guid? QuantityUnitId { get; set; }
        public string? AttributesXml { get; set; }
        public int StockQuantity { get; set; }
        public bool AllowOutOfStockOrders { get; set; }
        public DateTime CreatedDate { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public Guid? CreatedBy { get; set; }
        public Guid? UpdatedBy { get; set; }

        public virtual DeliveryTime DeliveryTime { get; set; }
        public virtual Product Product { get; set; }
        public virtual Unit QuantityUnit { get; set; }
    }
}