// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using VFi.NetDevPack.Domain;
using System;
using System.Collections.Generic;

namespace VFi.Domain.PIM.Models
{
    public partial class ProductInventory : Entity, IAggregateRoot
    {
        public ProductInventory()
        {
            ProductInventoryDetail = new HashSet<ProductInventoryDetail>();
        }
         
        public Guid? WarehouseId { get; set; }
        public Guid? ProductId { get; set; }
        public Guid? UnitId { get; set; }
        public decimal? StockQuantity { get; set; }
        public decimal? ReservedQuantity { get; set; }
        public decimal? PlannedQuantity { get; set; }
        public DateTime CreatedDate { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public Guid? CreatedBy { get; set; }
        public Guid? UpdatedBy { get; set; }
        public string CreatedByName { get; set; }
        public string UpdatedByName { get; set; }
        public decimal? Quantity1 { get; set; }
        public decimal? Quantity2 { get; set; }
        public decimal? Quantity3 { get; set; }
        /// <summary>
        /// Mã quy cách 1
        /// </summary>
        public string SpecificationCode1 { get; set; }
        /// <summary>
        /// Mã quy cách 1
        /// </summary>
        public string SpecificationCode2 { get; set; }
        /// <summary>
        /// Mã quy cách 1
        /// </summary>
        public string SpecificationCode3 { get; set; }
        /// <summary>
        /// Mã quy cách 1
        /// </summary>
        public string SpecificationCode4 { get; set; }
        /// <summary>
        /// Mã quy cách 1
        /// </summary>
        public string SpecificationCode5 { get; set; }
        /// <summary>
        /// Mã quy cách 1
        /// </summary>
        public string SpecificationCode6 { get; set; }
        /// <summary>
        /// Mã quy cách 1
        /// </summary>
        public string SpecificationCode7 { get; set; }
        /// <summary>
        /// Mã quy cách 1
        /// </summary>
        public string SpecificationCode8 { get; set; }
        /// <summary>
        /// Mã quy cách 1
        /// </summary>
        public string SpecificationCode9 { get; set; }
        public string SpecificationCode10 { get; set; }

        public virtual Product Product { get; set; }
        public virtual Warehouse Warehouse { get; set; }
        public virtual Unit Unit { get; set; }
        public virtual ICollection<ProductInventoryDetail> ProductInventoryDetail { get; set; }
    }
}