// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using VFi.NetDevPack.Domain;
using System;
using System.Collections.Generic;

namespace VFi.Domain.PIM.Models
{
    public partial class ProductInventoryDetail : Entity, IAggregateRoot
    {
        public Guid? ProductInventoryId { get; set; }
        public string LotNumber { get; set; }
        public DateTime? ExpireDate { get; set; }
        public double? Quantity { get; set; }
        public string UnitType { get; set; }
        /// <summary>
        /// Đơn vị tính
        /// </summary>
        public string UnitCode { get; set; }
        public string UnitName { get; set; }
        public DateTime? CreatedDate { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public Guid? CreatedBy { get; set; }
        public Guid? UpdatedBy { get; set; }
        public string CreatedByName { get; set; }
        public string UpdatedByName { get; set; }

        public virtual ProductInventory ProductInventory { get; set; }
    }
}