// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using VFi.NetDevPack.Domain;
using System;
using System.Collections.Generic;

namespace VFi.Domain.PIM.Models
{
    public partial class ProductWarehouse : Entity, IAggregateRoot
    {
        public Guid WarehouseId { get; set; }
        public Guid ProductId { get; set; }
        public int? StockQuantity { get; set; }
        public int? ReservedQuantity { get; set; }
        /// <summary>
        /// Số lượng kế hoạch
        /// </summary>
        public int? PlannedQuantity { get; set; }
        public Guid? CreatedBy { get; set; }
        public string CreatedName { get; set; }
        public Guid? UpdatedBy { get; set; }
        public string UpdatedName { get; set; }
        public DateTime? CreatedByDate { get; set; }
        public DateTime? UpdatedByDate { get; set; }

        public virtual Product Product { get; set; }
        public virtual Warehouse Warehouse { get; set; }
    }
}