// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using VFi.NetDevPack.Domain;
using System;
using System.Collections.Generic;

namespace VFi.Domain.PIM.Models
{
    public partial class ProductReviewHelpfulness : Entity, IAggregateRoot
    {
        public Guid ProductReviewId { get; set; }
        public bool WasHelpful { get; set; }

        public virtual ProductReview ProductReview { get; set; }
    }
}