// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using VFi.NetDevPack.Domain;
using System;
using System.Collections.Generic;

namespace VFi.Domain.PIM.Models
{
    public partial class ProductAttribute : Entity, IAggregateRoot
    {
        public ProductAttribute()
        {
            ProductAttributeOption = new HashSet<ProductAttributeOption>();
            ProductProductAttributeMapping = new HashSet<ProductProductAttributeMapping>();
        }
         
        public string Code { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Alias { get; set; }
        public bool AllowFiltering { get; set; }
        public int? SearchType { get; set; }
        public bool? IsOption { get; set; }
        public int DisplayOrder { get; set; }
        public string Mapping { get; set; }
        public DateTime CreatedDate { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public Guid? CreatedBy { get; set; }
        public Guid? UpdatedBy { get; set; }
        public int? Status { get; set; }
        public string CreatedByName { get; set; }
        public string UpdatedByName { get; set; }

        public virtual ICollection<ProductAttributeOption> ProductAttributeOption { get; set; }
        public virtual ICollection<ProductProductAttributeMapping> ProductProductAttributeMapping { get; set; }
    }
}