// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using VFi.NetDevPack.Domain;
using System;
using System.Collections.Generic;

namespace VFi.Domain.PIM.Models
{
    public partial class ProductTopicDetail : Entity, IAggregateRoot
    {
        public string ProductType { get; set; }
        public Guid ProductTopicId { get; set; }
        public string ProductTopic { get; set; }
        public string Code { get; set; }
        /// <summary>
        /// New = 0, Refurbished = 10, Used = 20, Damaged = 30
        /// </summary>
        public int Condition { get; set; }
        public string Unit { get; set; }
        public string Name { get; set; }
        public string SourceLink { get; set; }
        public string SourceCode { get; set; }
        public string ShortDescription { get; set; }
        public string FullDescription { get; set; }
        public string Keywords { get; set; }
        public string Origin { get; set; }
        public string Brand { get; set; }
        public string Manufacturer { get; set; }
        public string Image { get; set; }
        public string Images { get; set; }
        public decimal? Price { get; set; }
        public string Currency { get; set; }
        public int Status { get; set; }
        public Guid? CreatedBy { get; set; }
        public string CreatedByName { get; set; }
        public Guid? UpdatedBy { get; set; }
        public string UpdatedByName { get; set; }
        public DateTime? CreatedDate { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public string Tags { get; set; }
        public DateTime? Exp { get; set; }
        public decimal? BidPrice { get; set; }
        public int? Tax { get; set; }
        public string Channel { get; set; }
        public decimal? ShippingFee { get; set; }
        public int? Bids { get; set; }
        public DateTime? PublishDate { get; set; }
        public string TopicQuery { get; set; }
        public string Seller { get; set; }

        public virtual ProductTopic ProductTopicNavigation { get; set; }
    }
}