// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using VFi.NetDevPack.Domain;
using System;
using System.Collections.Generic;

namespace VFi.Domain.PIM.Models
{
    public partial class Product : Entity, IAggregateRoot
    {
        public Product()
        {
            ProductCategoryMapping = new HashSet<ProductCategoryMapping>();
            ProductGroupCategoryMapping = new HashSet<ProductGroupCategoryMapping>();
            ProductInventory = new HashSet<ProductInventory>();
            ProductMedia = new HashSet<ProductMedia>();
            ProductPackage = new HashSet<ProductPackage>();
            ProductProductAttributeMapping = new HashSet<ProductProductAttributeMapping>();
            ProductProductTagMapping = new HashSet<ProductProductTagMapping>();
            ProductReview = new HashSet<ProductReview>();
            ProductServiceAdd = new HashSet<ProductServiceAdd>();
            ProductSpecificationAttributeMapping = new HashSet<ProductSpecificationAttributeMapping>();
            ProductSpecificationCode = new HashSet<ProductSpecificationCode>();
            ProductStoreMapping = new HashSet<ProductStoreMapping>();
            ProductWarehouse = new HashSet<ProductWarehouse>();
            TierPrice = new HashSet<TierPrice>();
        }

        public string? Code { get; set; }
        public Guid? ProductTypeId { get; set; }
        /// <summary>
        /// SimpleProduct = 0, GroupedProduct = 10, Reservation = 20, BundledProduct = 30, Auction = 40
        /// </summary>
        public string ProductType { get; set; } = null!;
        public bool? ForBuy { get; set; }
        public bool? ForSale { get; set; }
        public bool? ForProduction { get; set; }
        /// <summary>
        /// New = 0, Refurbished = 10, Used = 20, Damaged = 30
        /// </summary>
        public int? Condition { get; set; }
        public string UnitType { get; set; }
        public Guid? UnitId { get; set; }
        public string? UnitCode { get; set; }
        public string Name { get; set; } = null!;
        public string? SourceLink { get; set; }
        public string? SourceCode { get; set; }
        public string? ShortDescription { get; set; }
        public string? FullDescription { get; set; }
        public string? LimitedToStores { get; set; }
        public Guid? CategoryRootId { get; set; }
        public string? CategoryRoot { get; set; }
        public string? IdGroupCategories { get; set; }
        public string? GroupCategories { get; set; }
        public string? Categories { get; set; }
        public string? IdCategories { get; set; }
        public string? Origin { get; set; }
        public Guid? OriginId { get; set; }
        public Guid? BrandId { get; set; }
        public string? Brand { get; set; }
        public Guid? ManufacturerId { get; set; }
        public string? Manufacturer { get; set; }
        /// <summary>
        /// Mã số linh kiện của nhà sản xuất
        /// </summary>
        public string? ManufacturerNumber { get; set; }
        public string? Image { get; set; }
        public decimal? ProductCost { get; set; }
        public string? CurrencyCost { get; set; }
        public decimal? Price { get; set; }
        public bool? HasTierPrices { get; set; }
        public string? Currency { get; set; }
        public bool? IsTaxExempt { get; set; }
        public Guid? TaxCategoryId { get; set; }
        /// <summary>
        /// Is Electronic Service
        /// </summary>
        public bool? IsEsd { get; set; }
        public decimal? OrderMinimumQuantity { get; set; }
        public decimal? OrderMaximumQuantity { get; set; }
        /// <summary>
        /// Bước số lượng
        /// </summary>
        public decimal? QuantityStep { get; set; }
        /// <summary>
        /// Manage inventory method
        /// </summary>
        public decimal? ManageInventoryMethodId { get; set; }
        public bool? UseMultipleWarehouses { get; set; }
        public Guid? WarehouseId { get; set; }
        public string? Warehouse { get; set; }
        /// <summary>
        /// GTIN (global trade item number)
        /// </summary>
        public string? Gtin { get; set; }
        public string? Sku { get; set; }
        /// <summary>
        /// Số lượng tồn kho
        /// </summary>
        public decimal? StockQuantity { get; set; }
        /// <summary>
        /// Số lượng đặt trước
        /// </summary>
        public decimal? ReservedQuantity { get; set; }
        /// <summary>
        /// Số lượng kế hoạch
        /// </summary>
        public decimal? PlannedQuantity { get; set; }
        public bool? MultiPacking { get; set; }
        /// <summary>
        /// Số kiện
        /// </summary>
        public int? Packages { get; set; }
        public decimal? Weight { get; set; }
        public decimal? Length { get; set; }
        public decimal? Width { get; set; }
        public decimal? Height { get; set; }
        public Guid? DeliveryTimeId { get; set; }
        public bool? IsShipEnabled { get; set; }
        public bool? IsFreeShipping { get; set; }
        public decimal? AdditionalShippingCharge { get; set; }
        public bool? CanReturn { get; set; }
        /// <summary>
        /// Số thế hải quan
        /// </summary>
        public string CustomsTariffNumber { get; set; }
        public bool? Deleted { get; set; }
        public DateTime? DeletedDate { get; set; }
        public int? Status { get; set; }
        public Guid? CreatedBy { get; set; }
        public string? CreatedByName { get; set; }
        public Guid? UpdatedBy { get; set; }
        public string? UpdatedByName { get; set; }
        public DateTime? CreatedDate { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public string? Combinations { get; set; }
        public string? Tags { get; set; }
        public bool? LotSerial { get; set; }
        public string? AttributesJson { get; set; }
        public int? VariantCount { get; set; }
        public bool? IsVariant { get; set; }
        public Guid? ParentId { get; set; }
        /// <summary>
        /// Khi mua hàng về, làm đề nghị nhập có phải kiểm tra QC không: 1 - Có. 0 - Không
        /// </summary>
        public bool? IsQc { get; set; }

        public virtual ProductBrand BrandNavigation { get; set; }
        public virtual CategoryRoot CategoryRootNavigation { get; set; }
        public virtual DeliveryTime DeliveryTime { get; set; }
        public virtual Manufacturer ManufacturerNavigation { get; set; }
        public virtual ProductOrigin OriginNavigation { get; set; }
        public virtual ProductType ProductTypeNavigation { get; set; }
        public virtual TaxCategory TaxCategory { get; set; }
        public virtual Unit Unit { get; set; }
        public virtual ICollection<ProductCategoryMapping> ProductCategoryMapping { get; set; }
        public virtual ICollection<ProductGroupCategoryMapping> ProductGroupCategoryMapping { get; set; }
        public virtual ICollection<ProductInventory> ProductInventory { get; set; }
        public virtual ICollection<ProductMedia> ProductMedia { get; set; }
        public virtual ICollection<ProductPackage> ProductPackage { get; set; }
        public virtual ICollection<ProductProductAttributeMapping> ProductProductAttributeMapping { get; set; }
        public virtual ICollection<ProductProductTagMapping> ProductProductTagMapping { get; set; }
        public virtual ICollection<ProductReview> ProductReview { get; set; }
        public virtual ICollection<ProductServiceAdd> ProductServiceAdd { get; set; }
        public virtual ICollection<ProductSpecificationAttributeMapping> ProductSpecificationAttributeMapping { get; set; }
        public virtual ICollection<ProductSpecificationCode> ProductSpecificationCode { get; set; }
        public virtual ICollection<ProductStoreMapping> ProductStoreMapping { get; set; }
        public virtual ICollection<ProductWarehouse> ProductWarehouse { get; set; }
        public virtual ICollection<TierPrice> TierPrice { get; set; }
    }
}