// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using VFi.NetDevPack.Domain;
using System;
using System.Collections.Generic;

namespace VFi.Domain.PIM.Models
{
    public partial class ProductProductAttributeMapping : Entity, IAggregateRoot
    {
        public ProductProductAttributeMapping()
        {
            ProductVariantAttributeValue = new HashSet<ProductVariantAttributeValue>();
        }
         
        public Guid ProductId { get; set; }
        public Guid ProductAttributeId { get; set; }
        public string TextPrompt { get; set; }
        public string CustomData { get; set; }
        public bool IsRequired { get; set; }
        public int AttributeControlTypeId { get; set; }
        public int DisplayOrder { get; set; }

        public virtual Product Product { get; set; }
        public virtual ProductAttribute ProductAttribute { get; set; }
        public virtual ICollection<ProductVariantAttributeValue> ProductVariantAttributeValue { get; set; }
    }
}