// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using VFi.NetDevPack.Domain;
using System;
using System.Collections.Generic;

namespace VFi.Domain.PIM.Models
{
    public partial class ProductSpecificationAttributeMapping : Entity, IAggregateRoot
    {
        public Guid? SpecificationAttributeId { get; set; }
        public Guid SpecificationAttributeOptionId { get; set; }
        public Guid ProductId { get; set; }
        public int DisplayOrder { get; set; }

        public virtual Product Product { get; set; }
        public virtual SpecificationAttributeOption SpecificationAttributeOption { get; set; }
    }
}