// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using VFi.NetDevPack.Domain;
using System;
using System.Collections.Generic;

namespace VFi.Domain.PIM.Models
{
    public partial class ProductServiceAdd : Entity, IAggregateRoot
    {
        public Guid? ProductId { get; set; }
        public Guid? ServiceAddId { get; set; }
        public int? PayRequired { get; set; }
        public decimal? Price { get; set; }
        public decimal? MaxPrice { get; set; }
        public int CalculationMethod { get; set; }
        public string PriceSyntax { get; set; }
        public decimal? MinPrice { get; set; }
        public string Currency { get; set; }
        public int? Status { get; set; }
        public DateTime CreatedDate { get; set; }
        public Guid? CreatedBy { get; set; }
        public Guid? UpdatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public string UpdatedByName { get; set; }
        public string CreatedByName { get; set; }

        public virtual Product Product { get; set; }
        public virtual ServiceAdd ServiceAdd { get; set; }
    }
}