// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using VFi.NetDevPack.Domain;
using System;
using System.Collections.Generic;

namespace VFi.Domain.PIM.Models
{
    public partial class ProductCategoryMapping : Entity, IAggregateRoot
    {
        public Guid CategoryId { get; set; }
        public Guid ProductId { get; set; }
        public int DisplayOrder { get; set; }
        public Guid? GroupCategoryId { get; set; }

        public virtual Category Category { get; set; }
        public virtual Product Product { get; set; }
    }
}