// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using VFi.NetDevPack.Domain;
using System;
using System.Collections.Generic;

namespace VFi.Domain.PIM.Models
{
    public partial class ServiceAddPriceSyntax : Entity, IAggregateRoot
    {
        public string Code { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        /// <summary>
        /// Kiểu giá trị: 0-Số, 1-Tiền tệ, 2-Phần trăm, 3-Chữ, 4-Ngày, 5-Checkbox
        /// </summary>
        public int TypeValue { get; set; }
        /// <summary>
        /// Công thức
        /// </summary>
        public string Formula { get; set; }
        public Guid? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public string CreatedName { get; set; }
        public Guid? UpdatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public string UpdatedName { get; set; }
    }
}