// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace VFi.Domain.PIM.Models
{
    public partial class SP_COUNT_PRODUCTS
    {
        public Guid Id { get; set; }
        public int? Total { get; set; }
        public int? ForBuy { get; set; }
        public int? ForSale { get; set; }
        public int? ForProduction { get; set; }
    }
}
