// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace VFi.Domain.PIM.Models
{
    public partial class SP_GET_TOP_MANUFACTURER
    {
        public Guid Id { get; set; }
        public string? Name { get; set; }
        public int? TopManuFacturer { get; set; }
    }
}
