// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace VFi.Domain.PIM.Models
{
    public partial class SP_GET_INVENTORY_DETAIL
    {
        public Guid Id { get; set; }
        public Guid? WarehouseId { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public Guid? ProductId { get; set; }
        public decimal? StockQuantity { get; set; }
        public decimal? ReservedQuantity { get; set; }
        public decimal? PlannedQuantity { get; set; }
    }
}
