// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace VFi.Domain.PIM.Models
{
    public partial class SP_GET_PRODUCT_PRICE_COST_BY_LISTID
    {
        public Guid Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public decimal? ProductCost { get; set; }
        public Guid? UnitId { get; set; }
        public string CurrencyCost { get; set; }
    }
}
