// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace VFi.Domain.PIM.Models
{
    public partial class SP_GET_TOP_PRODUCTS_INVENTORY
    {
        public Guid Id { get; set; }
        public string? Image { get; set; }
        public string? Code { get; set; }
        public string? Name { get; set; }
        public string? Origin { get; set; }
        public decimal? StockQuantity { get; set; }
    }
}
