// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using VFi.NetDevPack.Domain;
using System;
using System.Collections.Generic;

namespace VFi.Domain.PIM.Models
{
    public partial class TierPrice : Entity, IAggregateRoot
    {
        public Guid ProductId { get; set; }
        public Guid? StoreId { get; set; }
        public int Quantity { get; set; }
        public decimal Price { get; set; }
        public int CalculationMethod { get; set; }
        public DateTime? StartDate { get; set; }
        public DateTime? EndDate { get; set; }
        public DateTime? CreatedDate { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public Guid? CreatedBy { get; set; }
        public Guid? UpdatedBy { get; set; }
        public string UpdatedByName { get; set; }
        public string CreatedByName { get; set; }

        public virtual Product Product { get; set; }
        public virtual Store Store { get; set; }
    }
}