// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using VFi.NetDevPack.Domain;
using System;
using System.Collections.Generic;

namespace VFi.Domain.PIM.Models
{
    public partial class Unit : Entity, IAggregateRoot
    {
        public Unit()
        {
            Product = new HashSet<Product>();
            ProductInventory = new HashSet<ProductInventory>();
        }
         
        public string Code { get; set; }
        public string Name { get; set; }
        public string NamePlural { get; set; }
        public string Description { get; set; }
        public string DisplayLocale { get; set; }
        public int DisplayOrder { get; set; }
        public bool IsDefault { get; set; }
        public Guid? GroupUnitId { get; set; }
        public DateTime CreatedDate { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public Guid? CreatedBy { get; set; }
        public Guid? UpdatedBy { get; set; }
        public double? Rate { get; set; }
        public int Status { get; set; }
        public string CreatedByName { get; set; }
        public string UpdatedByName { get; set; }

        public virtual GroupUnit GroupUnit { get; set; }
        public virtual ICollection<Product> Product { get; set; }
        public virtual ICollection<ProductInventory> ProductInventory { get; set; }
    }
}